name: llm_workshop_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10  # Specify your preferred Python version
  - pip
  - pytorch 
  - transformers
  - accelerate>=0.21.0
  - pandas
  - numpy
  - seaborn
  - nltk
  - scikit-learn
  - ipykernel
  
  